# Generated by Django 2.2.8 on 2019-12-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
