# Generated by Django 2.2.8 on 2019-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191211_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='des',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
