# Generated by Django 2.2.8 on 2019-12-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191212_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categary',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categary',
            new_name='category',
        ),
    ]
